name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "First Greeting of the day is just 'Hi.'"
          secondGreeding : "I wonder if it makes to add another greeting but I will go for it. It is 'How are you feeling today?' "
          thirdGreeting: "Now, third greeting is entirely optional and very special. It shows rather actual interest, not the superficial one. 'I hope you have a good day ahead.'"
